image: node:latest 

stages:
    - test

test:
    stage: test
    script: 
        - npm run test
        - npm run lint
    cache:
        paths:
        - node_modules/
    only:
        - feature/
        - master
        - merge_requests